### ISSUE TITLE
.Net Framework + IS 4

### ISSUE THREAD

**Issue by borisgr04** [joaocolombo/IS4#1]
Hola Joao,

Es posible que una WebApi .Net Framework sea protegida por IS4 para implementar un SSO.

**Comment by joaocolombo** [comment]
Claro, é possível sim, trabalho com varias aplicações que tem a validação feita pelo IS4. Basta você enviar o token no header do request. Se você precisar de mais detalhes ou mais ajuda ficarei feliz em ajuda -ló.

**Comment by borisgr04** [comment]
Gracias por la pronta respuesta. A mi me funciona con una aplicación auto-hospedada pero cuando hago un proyecto para IIS no me esta funcionando. 

Si requiero tu colaboración adicional. 

Este proyecto no tiene el servidor IS4 y no me funcionó. No se que configuración se requiere.

Gracias.

**Comment by borisgr04** [comment]
Ya me funciono,


Tengo mi ejemplo en mi github.


Ing. Boris González Rivera
B&A Systems
Construimos Soluciones

MÓVIL: 318-8780177


Por nuestra seguridad:
Si decide reenviar este correo, colabore con dos tareas
1. Borre todas las direcciones que aparezcan en el contenido del correo, incluyendo esta cuesta.
2. Envie sus direcciones como copia oculta CCO

En cumplimiento de la Ley 527_99 ARTICULO 10. Los mensajes de datos ser??n admisibles como medios de prueba y su fuerza probatoria es la otorgada en las disposiciones del Cap??tulo VIII del T??tulo XIII, Secci??n Tercera, Libro Segundo del C??digo de Procedimiento Civil. En toda actuaci??n administrativa o judicial, no se negar?? eficacia, validez o fuerza obligatoria y probatoria a todo tipo de informaci??n en forma de un mensaje de datos, por el s??lo hecho que se trate de un mensaje de datos o en raz??n de no haber sido presentado en su forma original.


??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????




________________________________
De: João Rafael Colombo <notifications@github.com>
Enviado: viernes, 1 de junio de 2018 8:43:34 a.m.
Para: joaocolombo/IS4
Cc: borisgr04; Author
Asunto: Re: [joaocolombo/IS4] .Net Framework + IS 4 (#1)


Claro, é possível sim, trabalho com varias aplicações que tem a validação feita pelo IS4. Basta você enviar o token no header do request. Se você precisar de mais detalhes ou mais ajuda ficarei feliz em ajuda -ló.
